version: "3.8"

services:
  backend:
    build:
      context: ./assignment_expert_backend
    container_name: assignment_expert_backend_container
    expose:
      - "8000"
    env_file:
      - ./assignment_expert_backend/.env
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./assignment_expert_frontend
      dockerfile: Dockerfile.prod
    container_name: assignment_expert_frontend_container
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
