services:
  backend:
    build:
      context: ./assignment_expert_backend
    container_name: assignment_expert_backend_container
    expose:
      - "8000"
    env_file:
      - ./assignment_expert_backend/.env
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./assignment_expert_frontend
      dockerfile: Dockerfile.prod
    container_name: assignment_expert_frontend_container
    volumes:
      - frontend_dist:/app/dist
    depends_on:
      - backend
    command: sh -c "npm install && npm run build && tail -f /dev/null"

  nginx:
    image: nginx:alpine
    container_name: nginx_container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - frontend_dist:/usr/share/nginx/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx/ssl:/var/www/certbot
    depends_on:
      - frontend
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot_container
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx/ssl:/var/www/certbot
    entrypoint: sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot \
                       --email chandrakantabhoi10@gmail.com --agree-tos --no-eff-email \
                       -d assignmentpros.in -d www.assignmentpros.com"

volumes:
  frontend_dist:
  certbot-etc:
  certbot-var:
