version: "3.9"

services:
  backend:
    build:
      context: ./assignment_expert_backend
    container_name: assignment_expert_backend_cotainer
    ports:
      - "8000:8000"
    volumes:
      - ./assignment_expert_backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./assignment_expert_frontend
    container_name: assignment_expert_frontend_container
    ports:
      - "80:5173"  
