# Step 1: Build React app
FROM node:18 as build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Step 2: Output build folder only
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
