FROM node:18

WORKDIR /app

# Copy package files and install deps
COPY package*.json ./
RUN npm install

# Copy all source files
COPY . .

# We don’t run the build here because in your compose file
# you run `npm run build` at container startup (runtime)

CMD ["sh"]
